### ISSUE TITLE
libhostfxr.so not found

### ISSUE THREAD

**Issue by crummel** [crummel/source-build-tarball-2.0.5#1]
```
[chris@crummelrhclean testing]$ ./dotnet new console
Error:
  An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
    package: 'runtime.rhel.7.4-x64.Microsoft.NETCore.DotNetHostResolver', version: '2.0.5'
    path: 'runtimes/rhel.7.4-x64/native/libhostfxr.so'
```

**Comment by weshaggard** [comment]
I suspect it is because of https://github.com/crummel/source-build-tarball-2.0.5/blob/master/src/core-setup/src/sharedFramework/sharedFramework.proj#L136 being commented out.

**Comment by crummel** [comment]
Fixed in https://github.com/crummel/source-build-tarball-2.0.5/commit/9d984b0b3cf91cd8aa7d91aa11c406674255eb74
