### ISSUE TITLE
Nuget.Config has dirty locations

### ISSUE THREAD

**Issue by weshaggard** [crummel/source-build-tarball-2.0.5#3]
https://github.com/crummel/source-build-tarball-2.0.5/blob/09ca1a9d5d6c058372de7805162e47df691cf5de/src/core-setup/NuGet.config#L10

@crummel @dseefeld @dleeapho as FYI the Nuget.Config files have paths that are hard-coded to Chris' machine which we need to ensure get removed before final builds but also thought it might potentially cause differences when you guys test build this tarball. Not sure I can equate it with any particular issue right now but something to keep in mind.

**Comment by crummel** [comment]
We should fix this but I don't think it should be a problem in the short-term as the `AddSourceToNuGetConfig` task replaces the source if it already exists.

**Comment by dseefeld** [comment]
I also noticed this one:
https://github.com/crummel/source-build-tarball-2.0.5/blob/09ca1a9d5d6c058372de7805162e47df691cf5de/src/cli/build/package/Layout.targets#L23
I'm not sure if this will cause an issue.

**Comment by weshaggard** [comment]
The nuget.config files correctly update locations each time even if we are doing patching.
