### ISSUE TITLE
CLI MakeRelative path not found.

### ISSUE THREAD

**Issue by dseefeld** [crummel/source-build-tarball-2.0.5#6]
Tarball build failed with the following error:

  /src/source-build-tarball-2.0.5/src/cli/build/package/Layout.targets(55,5): error MSB4044: The "MakeRelative" task was not given a value for the required parameter "Path2". [/src/source-build-tarball-2.0.5/src/cli/build.proj] [/src/source-build-tarball-2.0.5/targets/repository.proj]
  /src/source-build-tarball-2.0.5/src/cli/build/package/Layout.targets(55,5): error MSB4044: The "MakeRelative" task was not given a value for the required parameter "Path2". [/src/source-build-tarball-2.0.5/src/cli/build.proj] [/src/source-build-tarball-2.0.5/targets/repository.proj]
  /src/source-build-tarball-2.0.5/targets/repository.proj(85,5): error MSB3073: The command "/src/source-build-tarball-2.0.5/src/cli/build.sh '/p:CLITargets="Prepare;Compile;Package"' /v:detailed /p:SkipBuildingInstallers=true /p:IncludeNuGetPackageArchive=false /p:IncludeAdditionalSharedFrameworks=false /flp:v=detailed /p:CoreSetupBlobRootUrl=file:///src/source-build-tarball-2.0.5/bin/obj/x64/Release/blobs/ /p:UsePortableLinuxSharedFramework=false /p:IncludeSharedFrameworksForBackwardsCompatibilityTests=false /p:IncludeAspNetCoreRuntime=false /p:IncludeMSBuildSdkResolver=false /p:Rid=rhel.7.4-x64 /p:CoreSetupRid=rhel.7.4-x64 /p:ProductMonikerRid=rhel.7.4-x64 /p:Configuration=Release" exited with code 1.

**Comment by dseefeld** [comment]
In https://github.com/crummel/source-build-tarball-2.0.5/blob/d999749056d053d6af61eeb3dc8d33feead29b05/src/cli/build/package/Layout.targets#L23, the hardcoded path is causing the issue with MakeRelative.  I've updated to a relative path based on $(OutputDirectory) and am retrying the build.

**Comment by livarcocc** [comment]
This is not hard-coded in the CLI code. Seems like a patch someone made to progress. Maybe @crummel

**Comment by dseefeld** [comment]
This is no longer an issue.
